<?php include("template/cabezera.php");?>

<div class="jumbotron">
        <h1 class="display-3">Bienvenidos a la biblioteca digital</h1>
          
        <img src="./img/bb1.jpg" class="img-fluid ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}" alt="">
        <hr class="my-2">

        <p class="lead">
            <a class="btn btn-primary btn-lg" href="./ayuda.php" role="button">ayuda</a>
        </p>
    </div>

<?php include("template/pie.php");?>

